@IdentityServer = http://localhost:5071

### Sign Up

POST {{IdentityServer}}/accounts
accept: */*
Content-Type: application/json

{
  "email": "levirgon@gmail.com",
  "password": "12345678",
  "firstName": "Manzur",
  "lastName": "Alahi"
}

### Sign In

POST {{IdentityServer}}/connect/token
Content-Type: application/x-www-form-urlencoded

username = levirgon%40gmail.com &
password = 12345678 &
grant_type = password &
scope = offline_access+core-scope &
client_id = postman &
client_secret = postman-secret

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Get User Profile

GET {{IdentityServer}}/accounts/manage/info
Authorization: Bearer {{access_token}}
accept: text/plain

### Get Refresh Token

POST {{IdentityServer}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = refresh_token &
scope = offline_access+core-scope &
client_id = postman &
client_secret = postman-secret &
refresh_token = {{refresh_token}}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Forgot Password

POST {{IdentityServer}}/accounts/forgot-password
accept: application/json
Content-Type: application/json

{
  "email": "levirgon@gmail.com"
}

> {%
    client.global.set("reset_token", response.body.data.resetToken);
%}

### Reset Password

POST {{IdentityServer}}/accounts/reset-password
accept: application/json
Content-Type: application/json

{
  "email": "levirgon@gmail.com",
  "token": "{{reset_token}}"
}

###


