@IdentityEndpoints = http://localhost:5048

### Sign Up

POST {{IdentityEndpoints}}/accounts
accept: */*
Content-Type: application/json

{
  "email": "manzur@gmail.com",
  "password": "12345678aA!",
  "firstName": "Manzur",
  "lastName": "Alahi"
}

### Sign In

POST {{IdentityEndpoints}}/connect/token?useCookies=false&useSessionCookies=false
accept: application/json
Content-Type: application/json

{
  "email": "levirgon@gmail.com",
  "password": "12345678aA!"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}


### Get User Profile
GET {{IdentityEndpoints}}/accounts/manage/info
Authorization: Bearer {{access_token}}
accept: application/json

### Get Refresh Token
POST {{IdentityEndpoints}}/connect/refresh-token
accept: application/json
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}

### Forgot Password

POST {{IdentityEndpoints}}/accounts/forgot-password
accept: application/json
Content-Type: application/json

{
  "email": "manzur@gmail.com"
}

> {%
    client.global.set("reset_token", response.body.data.resetToken);
%}

### Reset Password

POST {{IdentityEndpoints}}/accounts/reset-password
accept: application/json
Content-Type: application/json

{
  "email": "manzur@gmail.com",
  "token": "{{reset_token}}"
}

###






